name: Run Python script and push changes to another private repository

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
        python3 diff_level.py

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update directory structure"

    - name: Push changes to another private repository
      env:
        PAT: ${{ secrets.CODE_TRANSFER }} # Add your Personal Access Token as a secret
      run: |
        git remote add other_repo <other_repository_url>
        git push other_repo HEAD:master
