name: Run Python script and push changes to the same repository

on:
  push:
    branches:
      - master
    # Check for specific commit messages to skip workflow run
    paths-ignore:
      - '*.md'  # Example: Adjust the file pattern if needed
    if: >
      contains(github.event.head_commit.message, 'Attach NOTES - LeetHub') ||
      contains(github.event.head_commit.message, 'Create README - LeetHub')

jobs:
  run_script:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'Attach NOTES - LeetHub') && !contains(github.event.head_commit.message, 'Create README - LeetHub')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
        python3 srcipts/organize_files.py

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Organized Problem Solution according to Difficulty Level Folder Structure"

    - name: Push changes to the same branch
      run: |
        git push origin HEAD:master
