name: Run Python script on push

on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
        python3 diff_level.py
